version: '3.1'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

  redis:
    image: redis:7.2.1
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  customers-api:
    image: tadeifelipe/customers-wishlist:latest
    container_name: costumers-api
    ports:
      - 8081:8081

  products-api:
    image: tadeifelipe/products-wishlist:latest
    container_name: products-api
    ports:
      - 8082:8082

volumes:
  data: {}
  cache: {}